{% set name = "robert" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robert-{{ version }}.tar.gz
  sha256: 6b4717ced2bfa98bc787756c12a4a022a77f1f9fec5fa05527ef8358df8cbffa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base >=3.7,<3.8
    - pandas >=2.0.3,<2.1
    - numpy >=1.24,<1.25
    - progress
    - pyyaml
    - seaborn
    - scipy
    - scikit-learn ==1.3.0
    - hyperopt
    - numba >=0.57,<0.58
    - shap >=0.42,<0.43
    - glib
    - weasyprint
    - gtk3
    - pango

test:
  imports:
    - robert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jvalegre/robert
  summary: Refiner and Optimizer of a Bunch of Existing Regression Tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jvalegre
    - ddgunizar
