{% set name = "robert" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robert-{{ version }}.tar.gz
  sha256: fc59d604f78ab60680c7f6f9e71ab57c6bafd6d4cdcf0f15857fcca68fb92d89

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pyyaml
    - matplotlib-base >=3.7,<3.8
    - pandas ==2.2.2
    - numpy ==1.26.4
    - progress
    - seaborn
    - scipy
    - scikit-learn ==1.5.1
    - hyperopt
    - numba ==0.60.0
    - shap ==0.45.1
    - mapie ==0.8.6
    - glib
    - weasyprint
    - gtk3
    - pango
    - mscorefonts

test:
  imports:
    - robert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jvalegre/robert
  summary: Refiner and Optimizer of a Bunch of Existing Regression Tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jvalegre
    - ddgunizar
